name: Deploy Back-end

on:
  push:
    branches:
      - main
    paths:
      - "back-end/**"
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy back-end to Fly.io
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_APP_NAME: will-warner-portfolio
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install fly
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Verify fly
        run: fly version

      - name: Run fly launch for back-end
        run: |
          cd back-end
          fly deploy
          # fly launch --name "${FLY_APP_NAME}" --region "${FLY_REGION}" --copy-config --config fly.toml --yes || true
